name: Deploy ASP.NET App to VPS

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # or the version you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    - name: Add EF Core CLI to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    
    # Database update step
    - name: Update Database
      env:
        # Add your database connection string as a GitHub secret
        ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
      run: dotnet ef database update

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Publish the app
      run: dotnet publish -c Release -o ./publish


    - name: Setup SSH for deployment
      uses: webfactory/ssh-agent@v0.5.3  # Use the correct version
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VPS
      run: |
        scp -r ./publish user@your_vps_ip:/var/www/aspnetapp

    - name: Restart the ASP.NET app on VPS
      run: |
        ssh user@your_vps_ip 'sudo systemctl restart kestrel-aspnetapp.service'

    # Telegram Notification Step
    - name: Notify via Telegram
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="Deployment Successful for ASP.NET App on VPS"
