jobs:
  build:
    runs-on: ubuntu-latest
    env:
      systemctl_service_name: Backend
      app_port: 5051 # You can modify this port dynamically
      message: |
        [${{ github.event.head_commit.committer.name }}](https://github.com/${{github.event.head_commit.committer.username}}) pushed new commit:
        `[ ${{github.event.head_commit.message}} ]`
        to [${{ github.event.repository.name }}](https://github.com/${{ github.event.repository.html_url }})
    steps:
      # Previous steps ...

      - name: Stop .NET services
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl stop ${{ env.systemctl_service_name }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Modify service file to include the port
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            sudo sed -i 's|Environment=.*|Environment=ASPNETCORE_URLS=http://0.0.0.0:${{ env.app_port }}|' /etc/systemd/system/${{ env.systemctl_service_name }}.service
            sudo systemctl daemon-reload
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Copy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: deploy/*
          target: "/var/www/backend"
          overwrite: true

      - name: Start .NET services
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl start --no-block ${{ env.systemctl_service_name }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Send notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ env.message }}
          format: markdown
